GET http://127.0.0.1:8000/chat?message=안녕 지금부터 얘기를 해볼게
### 
GET http://127.0.0.1:8000/chat?message=활명수
### 
GET http://127.0.0.1:8000/chat?message=박카스에 대해서 알려줘
### 
GET http://127.0.0.1:8000/chat?message=바카스를 먹을때 부작용이 있나?
###
GET http://127.0.0.1:8000/chat?message=운수 좋은 날의 주인공은 누구인가요?
### 
GET http://127.0.0.1:8000/chat?message=그는 어떤 직업을 가지고 있었나요?
### 
GET http://127.0.0.1:8000/chat?message=그날 그는 무엇을 많이 했나요?
### 
GET http://127.0.0.1:8000/chat?message=박카스랑 활명수를 같이 먹어도 되나요?