### 
GET https://psychic-sniffle-g4q7pj7j9gwghp9v9-8000.app.github.dev/chat?message=활명수
### 
GET https://psychic-sniffle-g4q7pj7j9gwghp9v9-8000.app.github.dev/chat?message=신신티눈고(살리실산반창고)(수출명:SINSINCORNPLASTER)
###
GET https://psychic-sniffle-g4q7pj7j9gwghp9v9-8000.app.github.dev/chat?message=아네모정
###
GET https://psychic-sniffle-g4q7pj7j9gwghp9v9-8000.app.github.dev/chat?message=타치온정50밀리그램(글루타티온(환원형))
### 
GET https://psychic-sniffle-g4q7pj7j9gwghp9v9-8000.app.github.dev/chat?message=겔포스현탁액(인산알루미늄겔)
### 
GET https://psychic-sniffle-g4q7pj7j9gwghp9v9-8000.app.github.dev/chat?message=부루펜